Repository OCA/l10n-romania, pull requests merged in 2021-05, with the labels that each got.

#157 [IMP] smaller report lines
  l10n_ro_stock_report/report/stock_report_template.xml
Labels: approved, bot is merging ⏳

#160 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .flake8
  .isort.cfg
  .pre-commit-config.yaml
  currency_rate_update_RO_BNR/models/res_currency_rate_provider_RO_BNR.py
  l10n_ro_partner_create_by_vat/models/res_partner.py
  l10n_ro_stock_report/report/stock_report.py
Labels: bot is merging ⏳, help wanted, needs review

#156 [FIX] create many2many report lines
  l10n_ro_stock_report/report/stock_report.py
Labels: bot is merging ⏳

#158 [FIX] the rounding of price_unit may result in wrong price_unit_val_dif
  l10n_ro_stock_account/models/account_invoice.py
Labels: bot is merging ⏳
