Repository OCA/l10n-romania, pull requests merged in 2023-10, with the labels that each got.

#648 [14.0][FIX] fix cand se valideaza factura ce nu are sale/purchase
  l10n_ro_stock_account/models/account_move.py
Labels: bot is merging ⏳

#649 [16.0][FIX] fix cand se valideaza factura ce nu are sale/purchase
  l10n_ro_stock_account/models/account_move.py
Labels: bot is merging ⏳

#647 [15.0][FIX] fix cand se valideaza factura ce nu are sale/purchase
  l10n_ro_stock_account/models/account_move.py
Labels: bot is merging ⏳

#655 14.0 anaf token editabil
  l10n_ro_account_anaf_sync/controllers/anaf_oauth.py
  l10n_ro_account_anaf_sync/models/l10n_ro_account_anaf_sync.py
  l10n_ro_account_anaf_sync/static/src/json/postman.json
Labels: bot is merging ⏳

#657 16.0 anaf sync access token
  l10n_ro_account_anaf_sync/controllers/anaf_oauth.py
Labels: bot is merging ⏳

#629 [14.0][FIX] sa se calculeze vat_number la onchange vat, fix vat on payment
  l10n_ro_config/__manifest__.py
  l10n_ro_config/models/res_partner.py
  l10n_ro_config/views/res_partner_view.xml
Labels: bot is merging ⏳

#652 Fix company init
  l10n_ro_config/__manifest__.py
  l10n_ro_config/models/res_company.py
  l10n_ro_config/security/ro_menus_group.xml
  l10n_ro_payment_to_statement/__init__.py
  l10n_ro_payment_to_statement/__manifest__.py
  l10n_ro_payment_to_statement/tests/test_payment.py
  l10n_ro_stock_account/models/res_company.py
  l10n_ro_stock_account/tests/common.py
Labels: bot is merging ⏳

#663 [16.0][FIX] set stock_move_line_id in svl vacuum
  l10n_ro_stock_account/models/product_product.py
Labels: bot is merging ⏳

#661 [14.0][FIX] set stock_move_line_id in svl vacuum
  l10n_ro_stock_account/models/product_product.py
Labels: bot is merging ⏳

#664 update tax_groups_totals
  l10n_ro_account_report_invoice/__manifest__.py
  l10n_ro_account_report_invoice/views/invoice_report.xml
Labels: bot is merging ⏳

#646 [14.0][IMP] setare invoice_id si invoice_line_id pe SVL price difference
  l10n_ro_stock_account/models/stock_valuation_layer.py
  l10n_ro_stock_account_reception_in_progress/models/__init__.py
  l10n_ro_stock_account_reception_in_progress/models/stock_picking.py
  l10n_ro_stock_account_reception_in_progress/models/stock_valuation_layer.py
  l10n_ro_stock_price_difference/__manifest__.py
  l10n_ro_stock_price_difference/migrations/14.0.5.10.1/pre-migration.py
  l10n_ro_stock_price_difference/models/account_move.py
  l10n_ro_stock_price_difference/models/account_move_line.py
Labels: bot is merging ⏳

#666 [16.0][IMP] setare invoice_id si invoice_line_id pe SVL price difference
  l10n_ro_stock_account/models/stock_valuation_layer.py
  l10n_ro_stock_price_difference/__manifest__.py
  l10n_ro_stock_price_difference/migrations/16.0.5.4.1/pre-migration.py
  l10n_ro_stock_price_difference/models/account_move_line.py
Labels: bot is merging ⏳

#528 [14.0][FIX] delivery_notice in valuta sa verifice daca este inst…
  l10n_ro_stock_account_notice/models/stock_move.py
Labels: bot is merging ⏳

#662 [15.0][FIX] set stock_move_line_id in svl vacuum
  l10n_ro_stock_account/models/product_product.py
Labels: bot is merging ⏳

#667 [16.0][FIX] delivery_notice in valuta sa verifice daca este instalat …
  l10n_ro_stock_account_notice/models/stock_move.py
Labels: bot is merging ⏳

#529 [15.0][FIX] delivery_notice in valuta sa verifice daca este inst…
  l10n_ro_stock_account_notice/models/stock_move.py
Labels: bot is merging ⏳

#668 [16.0][UP]modiifcare ochange_stock_accounts
  l10n_ro_stock_account/models/product_category.py
Labels: bot is merging ⏳

#665 [15.0][IMP] setare invoice_id si invoice_line_id pe SVL price difference
  l10n_ro_stock_account/models/stock_valuation_layer.py
  l10n_ro_stock_account_reception_in_progress/models/__init__.py
  l10n_ro_stock_account_reception_in_progress/models/stock_picking.py
  l10n_ro_stock_account_reception_in_progress/models/stock_valuation_layer.py
  l10n_ro_stock_price_difference/__manifest__.py
  l10n_ro_stock_price_difference/migrations/15.0.5.4.1/pre-migration.py
  l10n_ro_stock_price_difference/models/account_move.py
  l10n_ro_stock_price_difference/models/account_move_line.py
Labels: bot is merging ⏳

#669 Corectie DVI
  l10n_ro_config/__manifest__.py
  l10n_ro_config/i18n/l10n_ro_config.pot
  l10n_ro_config/i18n/ro.po
  l10n_ro_config/migrations/15.0.2.8.1/pre-migration.py
  l10n_ro_config/models/res_company.py
  l10n_ro_config/models/res_config_settings.py
  l10n_ro_config/views/res_config_view.xml
  l10n_ro_dvi/__manifest__.py
  l10n_ro_dvi/i18n/l10n_ro_dvi.pot
  l10n_ro_dvi/i18n/ro.po
  l10n_ro_dvi/migrations/15.0.1.3.1/pre-migration.py
  l10n_ro_dvi/models/l10n_ro_account_dvi.py
  l10n_ro_dvi/models/res_company.py
  l10n_ro_dvi/models/stock_landed_cost.py
  l10n_ro_dvi/views/account_dvi_view.xml
  l10n_ro_payment_to_statement/models/account_journal.py
Labels: bot is merging ⏳

#670 14.0 update dvi
  l10n_ro_config/__manifest__.py
  l10n_ro_config/i18n/l10n_ro_config.pot
  l10n_ro_config/i18n/ro.po
  l10n_ro_config/migrations/14.0.2.10.1/pre-migration.py
  l10n_ro_config/models/res_company.py
  l10n_ro_config/models/res_config_settings.py
  l10n_ro_config/views/res_config_view.xml
  l10n_ro_dvi/__manifest__.py
  l10n_ro_dvi/i18n/l10n_ro_dvi.pot
  l10n_ro_dvi/i18n/ro.po
  l10n_ro_dvi/migrations/14.0.1.10.1/pre-migration.py
  l10n_ro_dvi/models/l10n_ro_account_dvi.py
  l10n_ro_dvi/models/res_company.py
  l10n_ro_dvi/models/stock_landed_cost.py
  l10n_ro_dvi/views/account_dvi_view.xml
  l10n_ro_payment_to_statement/models/account_journal.py
Labels: bot is merging ⏳

#672 [16.0][UP] update invoice_report
  l10n_ro_account_report_invoice/views/invoice_report.xml
Labels: bot is merging ⏳

#671 [15.0][UP] adaugare serii in stock report
  l10n_ro_stock_report/report/stock_report.py
  l10n_ro_stock_report/report/stock_report_view.xml
Labels: bot is merging ⏳

#673 [14.0][ADD] add l10n_ro_journal_register
  .flake8
  .pre-commit-config.yaml
  l10n_ro_journal_register/README.rst
  l10n_ro_journal_register/__init__.py
  l10n_ro_journal_register/__manifest__.py
  l10n_ro_journal_register/i18n/l10n_ro_journal_register.pot
  l10n_ro_journal_register/readme/CONTRIBUTORS.rst
  l10n_ro_journal_register/readme/DESCRIPTION.rst
  l10n_ro_journal_register/readme/INSTALL.rst
  l10n_ro_journal_register/report/__init__.py
  l10n_ro_journal_register/report/journal_register_report.py
  l10n_ro_journal_register/report/journal_register_report_view.xml
  l10n_ro_journal_register/security/ir.model.access.csv
  l10n_ro_journal_register/static/description/icon.png
  l10n_ro_journal_register/static/description/icon.svg
  l10n_ro_journal_register/static/description/index.html
  l10n_ro_journal_register/tests/__init__.py
  l10n_ro_journal_register/tests/test_journal_register.py
  setup/l10n_ro_journal_register/odoo/addons/l10n_ro_journal_register
  setup/l10n_ro_journal_register/setup.py
Labels: bot is merging ⏳

#677 [14.0][DEL] eliminare journal register
  l10n_ro_journal_register/README.rst
  l10n_ro_journal_register/__init__.py
  l10n_ro_journal_register/__manifest__.py
  l10n_ro_journal_register/i18n/l10n_ro_journal_register.pot
  l10n_ro_journal_register/readme/CONTRIBUTORS.rst
  l10n_ro_journal_register/readme/DESCRIPTION.rst
  l10n_ro_journal_register/readme/INSTALL.rst
  l10n_ro_journal_register/report/__init__.py
  l10n_ro_journal_register/report/journal_register_report.py
  l10n_ro_journal_register/report/journal_register_report_view.xml
  l10n_ro_journal_register/security/ir.model.access.csv
  l10n_ro_journal_register/static/description/icon.png
  l10n_ro_journal_register/static/description/icon.svg
  l10n_ro_journal_register/static/description/index.html
  l10n_ro_journal_register/tests/__init__.py
  l10n_ro_journal_register/tests/test_journal_register.py
  setup/l10n_ro_journal_register/odoo/addons/l10n_ro_journal_register
  setup/l10n_ro_journal_register/setup.py
Labels: bot is merging ⏳

#676 [15.0][DEL] eliminare journal register
  l10n_ro_journal_register/README.rst
  l10n_ro_journal_register/__init__.py
  l10n_ro_journal_register/__manifest__.py
  l10n_ro_journal_register/i18n/l10n_ro_journal_register.pot
  l10n_ro_journal_register/readme/CONTRIBUTORS.rst
  l10n_ro_journal_register/readme/DESCRIPTION.rst
  l10n_ro_journal_register/readme/INSTALL.rst
  l10n_ro_journal_register/report/__init__.py
  l10n_ro_journal_register/report/journal_register_report.py
  l10n_ro_journal_register/report/journal_register_report_view.xml
  l10n_ro_journal_register/security/ir.model.access.csv
  l10n_ro_journal_register/static/description/icon.png
  l10n_ro_journal_register/static/description/icon.svg
  l10n_ro_journal_register/static/description/index.html
  l10n_ro_journal_register/tests/__init__.py
  l10n_ro_journal_register/tests/test_journal_register.py
  setup/l10n_ro_journal_register/odoo/addons/l10n_ro_journal_register
  setup/l10n_ro_journal_register/setup.py
Labels: bot is merging ⏳

#680 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  l10n_ro_account_anaf_sync/i18n/l10n_ro_account_anaf_sync.pot
  l10n_ro_account_anaf_sync/security/account_security.xml
  l10n_ro_account_period_close/i18n/l10n_ro_account_period_close.pot
  l10n_ro_account_period_close/security/account_security.xml
  l10n_ro_account_period_close/views/account_period_close_view.xml
  l10n_ro_city/views/res_city_view.xml
  l10n_ro_config/views/common_report.xml
  l10n_ro_config/views/webclient_templates.xml
  l10n_ro_dvi/i18n/l10n_ro_dvi.pot
  l10n_ro_dvi/views/account_dvi_view.xml
  l10n_ro_dvi/views/account_invoice_view.xml
  l10n_ro_dvi/views/stock_landed_cost_view.xml
  l10n_ro_partner_create_by_vat/views/partner_view.xml
  l10n_ro_pos/views/assets.xml
  l10n_ro_siruta/i18n/l10n_ro_siruta.pot
  l10n_ro_siruta/views/assets.xml
  l10n_ro_siruta/views/l10n_ro_res_country_commune_views.xml
  l10n_ro_siruta/views/l10n_ro_res_country_zone_views.xml
  l10n_ro_siruta/views/partner_view.xml
  l10n_ro_stock_account/views/stock_location_view.xml
  l10n_ro_vat_on_payment/i18n/l10n_ro_vat_on_payment.pot
  l10n_ro_vat_on_payment/views/res_partner_view.xml
Labels: help wanted, needs review, bot is merging ⏳

#681 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  l10n_ro_account_anaf_sync/i18n/l10n_ro_account_anaf_sync.pot
  l10n_ro_dvi/i18n/l10n_ro_dvi.pot
Labels: help wanted, needs review

#682 Update from 14
  l10n_ro_account_edi_ubl/models/account_edi_format.py
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
  l10n_ro_account_edi_ubl/tests/test_acccount_edi_ubl.py
  l10n_ro_config/init_hook.py
  l10n_ro_config/models/res_partner.py
  l10n_ro_config/views/res_partner_view.xml
  l10n_ro_dvi/models/l10n_ro_account_dvi.py
  l10n_ro_fiscal_validation/models/res_partner.py
  l10n_ro_partner_create_by_vat/README.rst
  l10n_ro_partner_create_by_vat/readme/DESCRIPTION.rst
  l10n_ro_partner_create_by_vat/readme/USAGE.rst
  l10n_ro_partner_create_by_vat/static/description/index.html
  l10n_ro_partner_create_by_vat/tests/test_create_partner_by_vat.py
  l10n_ro_pos/static/src/xml/pos.xml
  l10n_ro_siruta/views/partner_view.xml
  l10n_ro_stock_account/models/account_move.py
  l10n_ro_stock_account/models/product_product.py
  l10n_ro_stock_account/models/stock_move.py
  l10n_ro_stock_account/models/stock_valuation_layer.py
  l10n_ro_stock_account/tests/common.py
  l10n_ro_stock_account/tests/test_svl_vacuum_location.py
  l10n_ro_stock_account_date_wizard/tests/test_stock_accounting_date.py
  l10n_ro_stock_account_reception_in_progress/views/purchase_order_view.xml
  l10n_ro_stock_picking_valued_report/tests/test_consum.py
  l10n_ro_stock_picking_valued_report/tests/test_purchase_stock_picking_valued.py
  l10n_ro_stock_report/report/stock_report.py
  l10n_ro_stock_report/tests/test_report_stock.py
Labels: bot is merging ⏳
