Repository OCA/l10n-romania, pull requests merged in 2024-02, with the labels that each got.

#833 [15.0] modificare export_cius_ro
  l10n_ro_account_edi_ubl/models/account_edi_format.py
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
Labels: bot is merging ⏳

#834 [16.0] modificare export_cius_ro
  l10n_ro_account_edi_ubl/models/account_edi_format.py
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
Labels: bot is merging ⏳

#835 [15.0] modificare _get_invoice_line_item_vals pentru taxarea inversa
  l10n_ro_account_edi_ubl/README.rst
  l10n_ro_account_edi_ubl/__manifest__.py
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
  l10n_ro_account_edi_ubl/static/description/index.html
Labels: bot is merging ⏳

#824 [14.0] imp fifo vacuum by location
  l10n_ro_stock_account/README.rst
  l10n_ro_stock_account/__manifest__.py
  l10n_ro_stock_account/models/product_product.py
  l10n_ro_stock_account/models/stock_move.py
  l10n_ro_stock_account/static/description/index.html
  l10n_ro_stock_account/tests/common.py
  l10n_ro_stock_account/tests/test_svl_vacuum_location.py
  l10n_ro_stock_account_notice/README.rst
  l10n_ro_stock_account_notice/__manifest__.py
  l10n_ro_stock_account_notice/models/stock_move.py
  l10n_ro_stock_account_notice/static/description/index.html
Labels: work in progress

#837 15.0 edi ubl invoice days
  l10n_ro_account_edi_ubl/models/account_edi_format.py
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
  l10n_ro_account_edi_ubl/tests/test_acccount_edi_ubl.py
Labels: bot is merging ⏳

#841 [16.0][FIX] fix OCA#840 register multiple payments
  l10n_ro_payment_to_statement/models/account_payment.py
Labels: bot is merging ⏳

#842 [15.0] [IMP] EDI UBL Update action
  l10n_ro_account_edi_ubl/README.rst
  l10n_ro_account_edi_ubl/__manifest__.py
  l10n_ro_account_edi_ubl/data/account_edi_data.xml
  l10n_ro_account_edi_ubl/migrations/15.0.1.40.1/post_migration.py
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
  l10n_ro_account_edi_ubl/static/description/index.html
Labels: bot is merging ⏳

#825 [15.0] imp fifo vacuum by location
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
  l10n_ro_stock_account/README.rst
  l10n_ro_stock_account/__manifest__.py
  l10n_ro_stock_account/models/product_product.py
  l10n_ro_stock_account/models/stock_move.py
  l10n_ro_stock_account/static/description/index.html
  l10n_ro_stock_account/tests/common.py
  l10n_ro_stock_account/tests/test_sale.py
  l10n_ro_stock_account/tests/test_svl_vacuum_location.py
Labels: work in progress, bot is merging ⏳

#843 [14.0] verificare daca e simple valuation sa nu faca svl pe diferenta
  l10n_ro_stock_account/README.rst
  l10n_ro_stock_account/__manifest__.py
  l10n_ro_stock_account/models/product_product.py
  l10n_ro_stock_account/static/description/index.html
  l10n_ro_stock_account/tests/test_sale.py
Labels: bot is merging ⏳

#849 [FIX][16.0] currency rate BNR cu link https
  currency_rate_update_RO_BNR/models/res_currency_rate_provider_RO_BNR.py
Labels: bot is merging ⏳

#855 [15.0][IMP] adaugare adresa de livrare in Efactura
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
Labels: merged 🎉

#852 modificare _get_aml_target_tax_account sa puna contul cash_basis_tran…
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
  l10n_ro_vat_on_payment/models/account_move.py
Labels: bot is merging ⏳

#848 [FIX][15.0] currency rate BNR cu link https
  currency_rate_update_RO_BNR/models/res_currency_rate_provider_RO_BNR.py
Labels: bot is merging ⏳

#856 [16.0][IMP] adaugare adresa de livrare in Efactura
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
Labels: bot is merging ⏳

#831 [17.0][FIX] currency_rate_update_RO_BNR: sync currency rates & proper tests
  currency_rate_update_RO_BNR/models/res_currency_rate_provider_RO_BNR.py
  currency_rate_update_RO_BNR/tests/nbrfxrates.xml
  currency_rate_update_RO_BNR/tests/nbrfxrates2022.xml
  currency_rate_update_RO_BNR/tests/nbrfxrates2023.xml
  currency_rate_update_RO_BNR/tests/nbrfxrates2024.xml
  currency_rate_update_RO_BNR/tests/test_currency_rate_update_ro_bnr.py
Labels: bot is merging ⏳

#860 Improve partner creation from EDI, fetching messages with pagination.
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
  l10n_ro_account_edi_ubl/models/res_company.py
Labels: bot is merging ⏳

#854 [16][IMPL]Download e-invoice zip ANAF - Facturi trimise
  l10n_ro_account_edi_ubl/models/account_edi_format.py
  l10n_ro_account_edi_ubl/models/res_company.py
  l10n_ro_account_edi_ubl/models/res_config_settings.py
  l10n_ro_account_edi_ubl/views/res_config_settings_views.xml
Labels: bot is merging ⏳

#845 14.0 upd from 15
  currency_rate_update_RO_BNR/tests/test_currency_rate_update_ro_bnr.py
  l10n_ro_account/models/account_payment.py
  l10n_ro_account_anaf_sync/models/l10n_ro_account_anaf_sync.py
  l10n_ro_account_anaf_sync/tests/test_account_anaf_sync.py
  l10n_ro_account_bank_statement_import_mt940_brd/models/mt940.py
  l10n_ro_account_bank_statement_import_mt940_rffsn/i18n/l10n_ro_account_bank_statement_import_mt940_brd.pot
  l10n_ro_account_edi_ubl/models/account_edi_format.py
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
  l10n_ro_account_edi_ubl/models/account_move.py
  l10n_ro_account_edi_ubl/tests/credit_note.xml
  l10n_ro_account_edi_ubl/tests/invoice.xml
  l10n_ro_account_edi_ubl/tests/test_acccount_edi_ubl.py
  l10n_ro_config/tests/test_bank_account_print_report.py
  l10n_ro_config/views/account_journal.xml
  l10n_ro_stock_account/models/product_product.py
  l10n_ro_stock_account_notice/tests/test_retur.py
  l10n_ro_stock_price_difference/tests/test_purchase.py
  l10n_ro_stock_report/report/stock_report.py
Labels: bot is merging ⏳

#861 [15.0] modificare _post_invoice_edi sa puna success False la facturil…
  l10n_ro_account_edi_ubl/models/account_edi_format.py
Labels: bot is merging ⏳

#865 14.0 edi code from 15
  l10n_ro_account_bank_statement_import_mt940_brd/data/specificatii_fisiere_ro.pdf
  l10n_ro_account_edi_ubl/data/account_edi_data.xml
  l10n_ro_account_edi_ubl/migrations/14.0.1.26.3/post_migration.py
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
  l10n_ro_account_edi_ubl/models/res_company.py
  l10n_ro_account_edi_ubl/tests/test_acccount_edi_ubl.py
Labels: bot is merging ⏳

#870 [16.0] verificare daca exista atasament ca altfel da eroare la print
  l10n_ro_account_edi_ubl/models/account_move.py
Labels: bot is merging ⏳

#869 [15.0] verificare daca exista atasament ca altfel da eroare la print
  l10n_ro_account_edi_ubl/models/account_move.py
Labels: bot is merging ⏳

#871 [15.0][IMP] Anexare ZIP la docu edi
  l10n_ro_account_edi_ubl/models/account_move.py
Labels: bot is merging ⏳

#872 [14.0] scoatere country_code
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
Labels: bot is merging ⏳
