Repository OCA/l10n-romania, pull requests merged in 2024-06, with the labels that each got.

#981 [16.0][FIX] fix access attachment
  l10n_ro_account_edi_ubl/models/account_edi_format.py
  l10n_ro_account_edi_ubl/models/account_move.py
Labels: bot is merging ⏳

#982 [16.0][FIX] fix vals_list["vals"]["sales_order_id"] - max 200 caractere
  l10n_ro_account_edi_ubl/__manifest__.py
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
  l10n_ro_account_edi_ubl/static/description/index.html
Labels: bot is merging ⏳

#983 modificare view
  l10n_ro_vat_on_payment/__manifest__.py
  l10n_ro_vat_on_payment/views/res_partner_view.xml
Labels: bot is merging ⏳

#984 [16.0][FIX] fix add to statement
  l10n_ro_payment_to_statement/__manifest__.py
  l10n_ro_payment_to_statement/models/account_move.py
  l10n_ro_payment_to_statement/models/account_payment.py
  l10n_ro_payment_to_statement/static/description/index.html
  l10n_ro_payment_to_statement/tests/test_payment.py
  l10n_ro_payment_to_statement/views/account_payment_view.xml
Labels: bot is merging ⏳

#986 [15.0][FIX] l10n_ro_stock_account_reception_in_progress auto_install False
  l10n_ro_stock_account_reception_in_progress/__manifest__.py
  l10n_ro_stock_account_reception_in_progress/static/description/index.html
Labels: bot is merging ⏳

#985 [16.0][IMP] Tratare eroare import xml
  l10n_ro_account_edi_ubl/models/res_company.py
Labels: bot is merging ⏳

#988 [16.0][FIX] fix la expirare token
  l10n_ro_account_anaf_sync/models/res_company.py
Labels: bot is merging ⏳

#987 [15.0][FIX] descaracare facturi
  l10n_ro_account_anaf_sync/models/res_company.py
  l10n_ro_account_edi_ubl/models/res_company.py
Labels: bot is merging ⏳

#978 16.0 translation
  l10n_ro_account_anaf_sync/i18n/ro.po
  l10n_ro_account_bank_statement_import_mt940_alpha/i18n/ro.po
  l10n_ro_account_bank_statement_import_mt940_base/i18n/ro.po
  l10n_ro_account_bank_statement_import_mt940_bcr/i18n/ro.po
  l10n_ro_account_bank_statement_import_mt940_brd/i18n/ro.po
  l10n_ro_account_bank_statement_import_mt940_ing/i18n/ro.po
  l10n_ro_account_bank_statement_import_mt940_rffsn/i18n/l10n_ro_account_bank_statement_import_mt940_brd.pot
  l10n_ro_account_bank_statement_import_mt940_rffsn/i18n/ro.po
  l10n_ro_account_bank_statement_report/i18n/ro.po
  l10n_ro_account_edi_ubl/i18n/ro.po
  l10n_ro_account_edit_currency_rate/i18n/ro.po
  l10n_ro_account_period_close/i18n/ro.po
  l10n_ro_account_report_invoice/i18n/ro.po
  l10n_ro_config/i18n/ro.po
  l10n_ro_dvi/i18n/ro.po
  l10n_ro_etransport/i18n/ro.po
  l10n_ro_fiscal_validation/i18n/ro.po
  l10n_ro_nondeductible_vat/i18n/ro.po
  l10n_ro_partner_create_by_vat/i18n/ro.po
  l10n_ro_partner_create_by_vat/i18n/ro_RO.po
  l10n_ro_payment_receipt_report/i18n/ro.po
  l10n_ro_payment_to_statement/i18n/ro.po
  l10n_ro_pos/i18n/ro.po
  l10n_ro_stock_account/i18n/ro.po
  l10n_ro_stock_account_date/i18n/ro.po
  l10n_ro_stock_account_date_wizard/i18n/ro.po
  l10n_ro_stock_account_landed_cost/i18n/ro.po
  l10n_ro_stock_account_mrp/i18n/ro.po
  l10n_ro_stock_account_notice/i18n/ro.po
  l10n_ro_stock_account_reception_in_progress/i18n/ro.po
  l10n_ro_stock_account_tracking/i18n/ro.po
  l10n_ro_stock_picking_comment_template/i18n/ro.po
  l10n_ro_stock_picking_valued_report/i18n/ro.po
  l10n_ro_stock_price_difference/i18n/ro.po
  l10n_ro_stock_report/i18n/ro.po
  l10n_ro_vat_on_payment/i18n/ro.po
Labels: work in progress, bot is merging ⏳

#990 [16.0][FIX] bank statement import mt 940: fix bank view
  l10n_ro_account_bank_statement_import_mt940_base/__manifest__.py
  l10n_ro_account_bank_statement_import_mt940_base/static/description/index.html
  l10n_ro_account_bank_statement_import_mt940_base/views/res_bank_view.xml
Labels: bot is merging ⏳

#991 [15.0][IMP] dezactivare rendare automata pdf anaf
  l10n_ro_account_edi_ubl/__manifest__.py
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
  l10n_ro_account_edi_ubl/models/account_move.py
  l10n_ro_account_edi_ubl/models/res_company.py
  l10n_ro_account_edi_ubl/models/res_config_settings.py
  l10n_ro_account_edi_ubl/static/description/index.html
  l10n_ro_account_edi_ubl/views/res_config_settings_views.xml
Labels: bot is merging ⏳

#992 [16.0][FIX] dezactivare generare automata PDF
  l10n_ro_account_edi_ubl/__manifest__.py
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
  l10n_ro_account_edi_ubl/models/account_move.py
  l10n_ro_account_edi_ubl/models/res_company.py
  l10n_ro_account_edi_ubl/models/res_config_settings.py
  l10n_ro_account_edi_ubl/static/description/index.html
  l10n_ro_account_edi_ubl/views/res_config_settings_views.xml
Labels: bot is merging ⏳

#993 [15.0][IMP] adaugare vendor_code in liniile de factura
  l10n_ro_account_edi_ubl/__manifest__.py
  l10n_ro_account_edi_ubl/i18n/ro.po
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
  l10n_ro_account_edi_ubl/models/account_move.py
  l10n_ro_account_edi_ubl/static/description/index.html
  l10n_ro_account_edi_ubl/views/account_invoice.xml
Labels: bot is merging ⏳

#994 [15.0][IMP] completare cod de furnizor
  l10n_ro_account_edi_ubl/models/account_move.py
Labels: bot is merging ⏳

#995 [16.0][IMP] adaugare vendor code
  l10n_ro_account_edi_ubl/__manifest__.py
  l10n_ro_account_edi_ubl/models/account_edi_xml_cius_ro.py
  l10n_ro_account_edi_ubl/models/account_move.py
  l10n_ro_account_edi_ubl/static/description/index.html
  l10n_ro_account_edi_ubl/views/account_invoice.xml
Labels: bot is merging ⏳

#989 [15.0][ADD] message spv
  l10n_ro_message_spv/README.rst
  l10n_ro_message_spv/__init__.py
  l10n_ro_message_spv/__manifest__.py
  l10n_ro_message_spv/data/ir_cron_data.xml
  l10n_ro_message_spv/models/__init__.py
  l10n_ro_message_spv/models/message_spv.py
  l10n_ro_message_spv/models/res_company.py
  l10n_ro_message_spv/readme/CONFIGURE.rst
  l10n_ro_message_spv/readme/CONTRIBUTORS.rst
  l10n_ro_message_spv/readme/DESCRIPTION.rst
  l10n_ro_message_spv/security/ir.model.access.csv
  l10n_ro_message_spv/security/security.xml
  l10n_ro_message_spv/static/description/icon.png
  l10n_ro_message_spv/static/description/icon.svg
  l10n_ro_message_spv/static/description/index.html
  l10n_ro_message_spv/static/src/js/message_spv.js
  l10n_ro_message_spv/views/message_spv_view.xml
  setup/l10n_ro_message_spv/odoo/addons/l10n_ro_message_spv
  setup/l10n_ro_message_spv/setup.py
Labels: bot is merging ⏳

#998 [15.0][FIX] fix completate supplierinfo
  l10n_ro_account_edi_ubl/models/account_move.py
Labels: bot is merging ⏳

#997 [16.0][MIG] mig l10n ro message spv
  l10n_ro_account_edi_ubl/models/account_move.py
  l10n_ro_message_spv/README.rst
  l10n_ro_message_spv/__init__.py
  l10n_ro_message_spv/__manifest__.py
  l10n_ro_message_spv/data/ir_cron_data.xml
  l10n_ro_message_spv/i18n/l10n_ro_message_spv.pot
  l10n_ro_message_spv/models/__init__.py
  l10n_ro_message_spv/models/message_spv.py
  l10n_ro_message_spv/models/res_company.py
  l10n_ro_message_spv/readme/CONFIGURE.rst
  l10n_ro_message_spv/readme/CONTRIBUTORS.rst
  l10n_ro_message_spv/readme/DESCRIPTION.rst
  l10n_ro_message_spv/security/ir.model.access.csv
  l10n_ro_message_spv/security/security.xml
  l10n_ro_message_spv/static/description/icon.png
  l10n_ro_message_spv/static/description/icon.svg
  l10n_ro_message_spv/static/description/index.html
  l10n_ro_message_spv/static/src/js/message_spv.js
  l10n_ro_message_spv/views/message_spv_view.xml
  setup/l10n_ro_message_spv/odoo/addons/l10n_ro_message_spv
  setup/l10n_ro_message_spv/setup.py
Labels: bot is merging ⏳

#1000 [17.0][FIX] fix po
  l10n_ro_account/i18n/ro.po
  l10n_ro_account_anaf_sync/i18n/ro.po
  l10n_ro_account_bank_statement_report/i18n/ro.po
  l10n_ro_config/i18n/ro.po
  l10n_ro_etransport/i18n/ro.po
  l10n_ro_partner_create_by_vat/i18n/ro.po
  l10n_ro_payment_to_statement/i18n/ro.po
  l10n_ro_pos/i18n/ro.po
  l10n_ro_stock/i18n/ro.po
  l10n_ro_stock_account/i18n/ro.po
  l10n_ro_stock_account_date/i18n/ro.po
  l10n_ro_stock_account_notice/i18n/ro.po
  l10n_ro_stock_report/i18n/ro.po
Labels: bot is merging ⏳

#1003 [16.0][IMP] traducere message spv
  l10n_ro_message_spv/__manifest__.py
  l10n_ro_message_spv/i18n/ro.po
  l10n_ro_message_spv/models/message_spv.py
  l10n_ro_message_spv/models/res_company.py
  l10n_ro_message_spv/static/description/index.html
  l10n_ro_message_spv/static/src/js/message_spv.esm.js
  l10n_ro_message_spv/static/src/js/message_spv.xml
  l10n_ro_message_spv/tests/__init__.py
  l10n_ro_message_spv/tests/test_message_spv.py
  l10n_ro_message_spv/views/message_spv_view.xml
Labels: bot is merging ⏳

#1005 [17.0][FIX] mesaje spv
  l10n_ro_message_spv/__manifest__.py
  l10n_ro_message_spv/i18n/ro.po
  l10n_ro_message_spv/models/message_spv.py
  l10n_ro_message_spv/models/res_company.py
  l10n_ro_message_spv/static/description/icon.png
  l10n_ro_message_spv/static/description/icon.svg
  l10n_ro_message_spv/static/description/index.html
Labels: bot is merging ⏳

#1007 [17.0] afisare mesaje
  l10n_ro_message_spv/models/message_spv.py
  l10n_ro_message_spv/views/message_spv_view.xml
Labels: bot is merging ⏳

#1009 [17.0][FIX] Corectie pentru creare factura
  l10n_ro_message_spv/models/message_spv.py
  l10n_ro_message_spv/views/message_spv_view.xml
Labels: bot is merging ⏳

#1010 [16.0][IMP] adaugare butoane de descarcare
  l10n_ro_message_spv/README.rst
  l10n_ro_message_spv/__manifest__.py
  l10n_ro_message_spv/data/ir_cron_data.xml
  l10n_ro_message_spv/i18n/ro.po
  l10n_ro_message_spv/models/message_spv.py
  l10n_ro_message_spv/models/res_company.py
  l10n_ro_message_spv/static/description/index.html
  l10n_ro_message_spv/tests/test_message_spv.py
  l10n_ro_message_spv/views/message_spv_view.xml
Labels: bot is merging ⏳

#1011 [15.0][IMP] adaugare butoane descarcare
  l10n_ro_message_spv/__manifest__.py
  l10n_ro_message_spv/models/message_spv.py
  l10n_ro_message_spv/static/description/index.html
  l10n_ro_message_spv/tests/__init__.py
  l10n_ro_message_spv/tests/test_message_spv.py
  l10n_ro_message_spv/views/message_spv_view.xml
Labels: bot is merging ⏳

#1013 [16.0][FIX] payment to statement: fix unlink with context
  l10n_ro_payment_to_statement/__manifest__.py
  l10n_ro_payment_to_statement/models/account_payment.py
  l10n_ro_payment_to_statement/static/description/index.html
Labels: bot is merging ⏳

#1015 [16.0][IMP] spv message
  l10n_ro_message_spv/models/message_spv.py
  l10n_ro_message_spv/views/message_spv_view.xml
Labels: bot is merging ⏳

#1014 [17.0][IMP] message SPV
  l10n_ro_message_spv/README.rst
  l10n_ro_message_spv/__manifest__.py
  l10n_ro_message_spv/models/message_spv.py
  l10n_ro_message_spv/static/description/index.html
  l10n_ro_message_spv/tests/invoice.zip
  l10n_ro_message_spv/tests/test_message_spv.py
  l10n_ro_message_spv/views/message_spv_view.xml
Labels: bot is merging ⏳

#1017 [16.0][FIX] Fix partner id
  l10n_ro_account_edi_ubl/models/account_move.py
Labels: needs review, bot is merging ⏳
