Repository OCA/l10n-romania, pull requests merged in 2025-04, with the labels that each got.

#1255 [18.0][FIX] corectie stornare livrare cu aviz, sa puna 707 pe debit
  l10n_ro_stock_account_notice/README.rst
  l10n_ro_stock_account_notice/models/product.py
  l10n_ro_stock_account_notice/models/stock_move.py
  l10n_ro_stock_account_notice/tests/test_sale.py
Labels: bot is merging ⏳

#1259 [17.0] sa nu mai faca nota pe diferenta de pret daca contul este acelasi
  l10n_ro_stock_account_landed_cost/models/stock_landed_cost.py
  l10n_ro_stock_account_reception_in_progress/models/purchase_order.py
Labels: bot is merging ⏳

#1260 [17.0][IMP] Adaugă creare document EDI pentru facturi fără documente existente
  l10n_ro_message_spv/models/message_spv.py
  l10n_ro_message_spv/models/res_company.py
  l10n_ro_message_spv/views/message_spv_view.xml
Labels: bot is merging ⏳

#1264 [17.0][IMP] Adaugă traducerile bulgare pentru l10n_ro_config
  l10n_ro_config/i18n/bg.po
  l10n_ro_config/i18n/de.po
  l10n_ro_config/i18n/el_GR.po
  l10n_ro_config/i18n/fr.po
  l10n_ro_config/i18n/it.po
Labels: bot is merging ⏳

#1265 18.0 mig l10n ro fiscal validation
  l10n_ro_fiscal_validation/README.rst
  l10n_ro_fiscal_validation/__init__.py
  l10n_ro_fiscal_validation/__manifest__.py
  l10n_ro_fiscal_validation/data/res_partner_vat_cron.xml
  l10n_ro_fiscal_validation/examples/res.partner.csv
  l10n_ro_fiscal_validation/i18n/l10n_ro_fiscal_validation.pot
  l10n_ro_fiscal_validation/i18n/ro.po
  l10n_ro_fiscal_validation/models/__init__.py
  l10n_ro_fiscal_validation/models/res_partner.py
  l10n_ro_fiscal_validation/pyproject.toml
  l10n_ro_fiscal_validation/readme/CONTRIBUTORS.md
  l10n_ro_fiscal_validation/readme/DESCRIPTION.md
  l10n_ro_fiscal_validation/readme/INSTALL.md
  l10n_ro_fiscal_validation/readme/USAGE.md
  l10n_ro_fiscal_validation/static/description/icon.png
  l10n_ro_fiscal_validation/static/description/index.html
  l10n_ro_fiscal_validation/tests/__init__.py
  l10n_ro_fiscal_validation/tests/test_partner_update_vat_subjected.py
Labels: merged 🎉

#1267 [18.0][IMP] Adaugă câmpul invoice_date și îmbunătățește logica facturilor
  l10n_ro_message_spv/__manifest__.py
  l10n_ro_message_spv/models/message_spv.py
  l10n_ro_message_spv/models/res_company.py
  l10n_ro_message_spv/views/message_spv_view.xml
Labels: bot is merging ⏳

#1269 [18.0][IMP] Elimină câmpul `is_l10n_ro_record` din resursele XML
  l10n_ro_config/i18n/bg.po
  l10n_ro_config/i18n/de.po
  l10n_ro_config/i18n/el_GR.po
  l10n_ro_config/i18n/fr.po
  l10n_ro_config/i18n/it.po
  l10n_ro_config/models/account_journal.py
  l10n_ro_config/models/res_partner.py
  l10n_ro_config/views/account_journal.xml
  l10n_ro_config/views/res_bank_view.xml
  l10n_ro_config/views/res_partner_view.xml
  l10n_ro_config/wizard/res_config_settings_views.xml
Labels: needs review, bot is merging ⏳

#1270 [18.0][IMP] Elimină câmpurile și codul comentat, actualizează funcționalități con…
  l10n_ro_stock/views/stock_location_view.xml
  l10n_ro_stock_account_notice/models/stock_move.py
  l10n_ro_stock_account_notice/views/stock_picking_view.xml
Labels: needs review, bot is merging ⏳

#1273 [18.0][IMP] Actualizează logica câmpului `l10n_ro_external_code`
  l10n_ro_account/models/account_account.py
Labels: bot is merging ⏳

#1271 [18.0][IMP] Actualizează logica salvării orașelor în res.partner
  l10n_ro_city/models/res_partner.py
  l10n_ro_city/views/res_city_view.xml
Labels: bot is merging ⏳

#1272 [18.0][IMP] Adaugă gestionarea poziției fiscale în funcționalitatea stock.
  l10n_ro_stock_account/models/account_move.py
  l10n_ro_stock_account/models/product_template.py
  l10n_ro_stock_account/models/stock_picking.py
  l10n_ro_stock_account/views/account_account_view.xml
  l10n_ro_stock_account/views/product_category_view.xml
  l10n_ro_stock_account/views/product_template_view.xml
  l10n_ro_stock_account/views/stock_location_view.xml
  l10n_ro_stock_account/views/stock_picking_view.xml
  l10n_ro_stock_account/views/stock_valuation_layer_views.xml
Labels: bot is merging ⏳

#1274 18.0 mig l10n ro stock account tracking
  l10n_ro_stock_account_tracking/README.rst
  l10n_ro_stock_account_tracking/__init__.py
  l10n_ro_stock_account_tracking/__manifest__.py
  l10n_ro_stock_account_tracking/i18n/l10n_ro_stock_account.pot
  l10n_ro_stock_account_tracking/i18n/l10n_ro_stock_account_tracking.pot
  l10n_ro_stock_account_tracking/i18n/ro.po
  l10n_ro_stock_account_tracking/init_hook.py
  l10n_ro_stock_account_tracking/models/__init__.py
  l10n_ro_stock_account_tracking/models/product_product.py
  l10n_ro_stock_account_tracking/models/stock_move.py
  l10n_ro_stock_account_tracking/models/stock_quant.py
  l10n_ro_stock_account_tracking/models/stock_valuation_layer.py
  l10n_ro_stock_account_tracking/models/stock_valuation_layer_tracking.py
  l10n_ro_stock_account_tracking/pyproject.toml
  l10n_ro_stock_account_tracking/readme/CONTRIBUTORS.md
  l10n_ro_stock_account_tracking/readme/DESCRIPTION.md
  l10n_ro_stock_account_tracking/security/ir.model.access.csv
  l10n_ro_stock_account_tracking/static/description/icon.png
  l10n_ro_stock_account_tracking/static/description/index.html
  l10n_ro_stock_account_tracking/tests/__init__.py
  l10n_ro_stock_account_tracking/tests/common.py
  l10n_ro_stock_account_tracking/tests/common2.py
  l10n_ro_stock_account_tracking/tests/test_consum.py
  l10n_ro_stock_account_tracking/tests/test_inventory.py
  l10n_ro_stock_account_tracking/tests/test_purchase.py
  l10n_ro_stock_account_tracking/tests/test_reception_return_not_fifo.py
  l10n_ro_stock_account_tracking/tests/test_retur.py
  l10n_ro_stock_account_tracking/tests/test_sale.py
  l10n_ro_stock_account_tracking/tests/test_sale_return_not_fifo.py
  l10n_ro_stock_account_tracking/tests/test_stock_quant_value.py
  l10n_ro_stock_account_tracking/tests/test_svl_vacuum_location.py
  l10n_ro_stock_account_tracking/views/stock_valuation_layer_views.xml
  l10n_ro_stock_account_tracking/wizard/__init__.py
  l10n_ro_stock_account_tracking/wizard/stock_picking_return.py
  l10n_ro_stock_account_tracking/wizard/stock_picking_return_views.xml
  l10n_ro_stock_account_tracking/wizard/stock_valuation_layer_revaluation.py
  l10n_ro_stock_account_tracking/wizard/stock_valuation_layer_revaluation_views.xml
Labels: bot is merging ⏳

#1277 [17.0][FIX] Simplifică filtrarea companiilor pentru descărcare SPV
  l10n_ro_message_spv/models/res_company.py
Labels: bot is merging ⏳

#1278 [18.0] modificare compute_account_id sa puna income pe sale
  l10n_ro_stock_account/models/account_move.py
Labels: bot is merging ⏳

#1281 [17.0][FIX] Corectează calculul prețului pentru mutările returnate
  l10n_ro_stock_account/models/stock_move.py
Labels: bot is merging ⏳

#1282 [18.0][FIX] Refactor gestionare coduri conturi și descărcare mesaje SPV
  l10n_ro_account/models/account_account.py
  l10n_ro_message_spv/models/res_company.py
Labels: bot is merging ⏳

#1283 [18.0][FIX] Actualizează câmpurile utilizate pentru datele de producție
  l10n_ro_stock_account_date/models/stock_move.py
Labels: bot is merging ⏳

#1276 [18.0]modificare get_view ca sa faca coloana invizibila daca e din tree
  l10n_ro_config/models/l10n_ro_mixin.py
Labels: bot is merging ⏳

#1280 [18.0]adaugare parametru l10n_ro_download_message_days pentru metoda …
  l10n_ro_message_spv/models/message_spv.py
Labels: bot is merging ⏳

#1279 [17.0] adaugare parametru l10n_ro_download_message_days pentru metoda…
  l10n_ro_config/models/l10n_ro_mixin.py
  l10n_ro_message_spv/models/message_spv.py
Labels: bot is merging ⏳

#1285 [15.0][IMP] Refactor type checking and add B2C handling for ANAF uploads
  l10n_ro_account_edi_ubl/models/account_edi_format.py
  l10n_ro_account_edi_ubl/models/account_move.py
Labels: bot is merging ⏳

#1287 [17.0][FIX] Corectează verificarea codului analitic în conturi
  l10n_ro_account/models/account_account.py
Labels: bot is merging ⏳
